spring:
  application:
    name: hello-spring-cloud-web-admin-fegin
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8805

feign:
  hystrix:
    enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/