spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.75.130:8084
  zipkin:
    base-url: http://192.168.75.130:9411

server:
  port: 8081

eureka:
  instance:
    hostname: 192.168.75.130
  client:
    # 表示是否将自己注册到 Eureka,因为要构建集群环境,需要将自己注册到集群,所以应该开启
    registerWithEureka: true
    # 表示是否从 Eureka 获取注册信息,如果不是单一节点,不需要同步其他 Eureka 节点,则可以设置为 false,但此处为集群,应该设置为 true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.75.130:8081/eureka/,http://192.168.75.130:8181/eureka/,http://192.168.75.130:8281/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info