spring:
  application:
    name: itoken-zipkin
  boot:
    admin:
      client:
        url: http://192.168.75.130:8084
  zipkin:
    base-url: http://192.168.75.130:9411

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.75.130:8081/eureka/,http://192.168.75.130:8181/eureka/,http://192.168.75.130:8281/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false