spring:
  application:
    name: hello-spring-cloud-eureka
server:
  port: 8801

eureka:
  instance:
    hostname: localhost
  client:
    # 通过 eureka.client.registerWithEureka:false 和 fetchRegistry:false 来表明自己是一个 Eureka Server
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

