spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Allen-HDs/spring-cloud-config
          search-paths: respo
          username: yx_endeavor@163.com
          password: liao5qiangua

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/