spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 8806

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/

zuul:
  routes:
    api-ribbon:
      path: /api/ribbon/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-feign:
      path: /api/feign/**
      serviceId: hello-spring-cloud-web-admin-fegin
