version: '3.1'
services:
  itoken-zuul:
    restart: always
    container_name: itoken-zuul
    image: 192.168.198.134:5000/itoken-zuul
    ports:
      - 8000:8000
    networks:
      - zuul_network
networks:
  zuul_network: