version: '3.1'
services:
  itoken-zipkin:
    restart: always
    container_name: itoken-zipkin
    image: 192.168.198.134:5000/itoken-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network
networks:
  zipkin_network:
